# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YB4rnbyU5sXtA9SY4-zfY01tsjRnYGuw
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/vendas_MCG_Papelaria.csv")

#Produtos mais vendidos (em quantidade e valor total)
produtos_mais_vendidos = df.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False)
produtos_maior_receita = df.groupby('Produto')['Valor Total'].sum().sort_values(ascending=False)

#Média de valor de compra por cliente
valor_medio_cliente = df.groupby('Cliente')['Valor Total'].mean()

#Desempenho por região (com base no endereço)
vendas_por_regiao = df.groupby('Endereço')['Valor_Total'].sum()

#Frequência de compras por cliente
frequencia_cliente = df['Cliente'].value_counts()

#Ticket médio geral
ticket_medio = df['Valor Total'].mean()

#Produtos mais comprados por cliente
produtos_por_cliente = df.groupby(['Cliente', 'Produto']).size().unstack().fillna(0)

 #Distribuição de preços dos produtos vendidos
df['Preço Unitário'].plot(kind='hist', bins=10)

#Vendas por intervalo de tempo (semanal, mensal, trimestral)
vendas_semanal = df.set_index('Data').resample('W')['Valor_Total'].sum()
vendas_mensal = df.set_index('Data').resample('M')['Valor_Total'].sum()

#Relação entre preço unitário e quantidade vendida
df.plot.scatter(x='Preço Unitário', y='Quantidade')